In [24]:
!pip install --upgrade scikit-learn

Requirement already up-to-date: sklearn in /usr/local/lib/python3.6/dist-packages (0.0)


In [2]:
from sklearn.datasets import load_iris
# from sklearn.linear_model import LogisticRegression
# from sklearn.linear_model import LogisticRegression
# from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
import numpy as np
import pandas as pd

In [3]:
iris = load_iris()
x, y = iris['data'], iris['target']

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
dataset = np.hstack((x, y.reshape(-1,1))) #เอาข้อมูล y มาต่อ test
np.random.shuffle(dataset)
x_train, x_test, y_train, y_test = train_test_split(dataset[:,:4],
                                                    dataset[:,4],
                                                    test_size = 0.2)


In [6]:
# model = LogisticRegression()
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [7]:
accuracy_score(y_test,y_pred)

1.0

In [8]:
joblib.dump(model,'iris.model')

['iris.model']

In [19]:
model.predict(np.array([[6.1, 3, 4.6, 1.4]]))

array([1.])

In [16]:
x_test

array([[6.8, 3. , 5.5, 2.1],
       [5.2, 2.7, 3.9, 1.4],
       [6. , 2.2, 5. , 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [7.3, 2.9, 6.3, 1.8],
       [5.5, 2.3, 4. , 1.3],
       [6.2, 2.2, 4.5, 1.5],
       [6.4, 2.8, 5.6, 2.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [5. , 2.3, 3.3, 1. ],
       [4.6, 3.6, 1. , 0.2],
       [6.1, 3. , 4.6, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [6.3, 2.3, 4.4, 1.3],
       [5.1, 3.5, 1.4, 0.2],
       [6. , 3.4, 4.5, 1.6],
       [4.9, 3.1, 1.5, 0.1],
       [4.7, 3.2, 1.6, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 2.4, 3.3, 1. ],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [5.8, 2.8, 5.1, 2.4]])

In [21]:
model = joblib.load("iris.model")

In [22]:
model.predict(np.array([[6.1, 3, 4.6, 1.4]]))

array([1.])